### ISSUE TITLE
Напомните что не так с стандартным?

### ISSUE THREAD

**Issue by ahvastunov-itmo** [Ashes1st/chat#2]
https://github.com/Ashes1st/chat/blob/f3603dca36cbf99333685d64c23661dd0e98250b/server.c#L99

**Comment by Ashes1st** [comment]
Эта функция не включена в стандарт и компилятор ругается при попытки использовать void* itoa(int input, char *buffer, int radix)

**Comment by ahvastunov-itmo** [comment]
http://www.cplusplus.com/reference/cstdlib/itoa/

**Comment by Ashes1st** [comment]
This function is not defined in ANSI-C and is not part of C++, but is supported by some compilers.
Мой компилятор видимо один из тех, что не поддерживает эту функцию.
